apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-software-hub-crds-student3
  namespace: openshift-gitops
spec:
  project: default

  sources:
    - repoURL: https://github.com/Aditt-197/lab3991.git
      targetRevision: main
      path: helm/install-software-hub-crds
      helm:
        releaseName: software-hub-crds-student3
        valueFiles:
          - $overrides/overrides/student3/values.yaml
    - repoURL: https://github.com/Aditt-197/lab3991.git
      targetRevision: main
      ref: overrides

  destination:
    server: https://kubernetes.default.svc
    namespace: cpd-student3

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
