global:
  operatorNamespace: cpd-operators
  instanceNamespace: cpd
  blockStorageClass: ocs-storagecluster-ceph-rbd
  fileStorageClass: ocs-storagecluster-cephfs-selinux-relabel
  imagePullPrefix: icr.io
  licenseType: Enterprise
  licenseAccept: true

imagePullSecrets: []

ibm_entitlement_key:
  secretKey: ibm_entitlement_key
  remoteRef:
    key: CT-DX-Shared/watsonx
    property: ibm_entitlement_key

analyticsengine:
  analyticsengine:
    autoScaleConfig: false
    scaleConfig: small
    serviceConfig:
      enableImagePrepull: true
      pullWxdImagesOnly: true
      informerEnabled: false
    sparkRuntimeConfig:
      maxDriverCpuCores: 5
      maxExecutorCpuCores: 5
      maxDriverMemory: "50g"
      maxExecutorMemory: "50g"
      maxNumWorkers: 50
    controlPlaneResourceConfig:
      resources:
        limits:
          cpu: '4'
          ephemeral-storage: 1Gi
          memory: 16Gi
        requests:
          cpu: '3'
          ephemeral-storage: 650Mi
          memory: 12Gi
    SparkMetaStoreEdb:
      minPoolSize: 20
      maxPoolSize: 50
      resources:
        requests:
          cpu: '2'
          ephemeral-storage: 200Mi
          memory: 4Gi
        limits:
          cpu: '4'
          ephemeral-storage: 700Mi
          memory: 8Gi
    deployerAgentConfig:
      contextTimeout: 50
      sleepInterval: 2000
      timeout: 300

ws-pipelines:
  wsPipelines:
    scaleConfig: small

watsonx-data:
  watsonxData:
    scaleConfig: small
    enable_watsonx_platform: true
    install_ccs_dependency: true

ws:
  ws:
    scaleConfig: small

