{{- if .Values.zen.zen.zenCustomRoute.route_host }}
{{- $caCert := (lookup "v1" "Secret" .Values.global.instanceNamespace "internal-tls") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cpd
  namespace: {{ .Values.global.instanceNamespace }}
  annotations:
    haproxy.router.openshift.io/timeout: 90s
spec:
  host: {{ .Values.zen.zen.zenCustomRoute.route_host }}
  port:
    targetPort: 8443
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
    {{- if $caCert }}
    destinationCACertificate: |
      {{ index $caCert.data "tls.crt" | b64dec | nindent 6 | trim }}
    {{- end }}
  to:
    kind: Service
    name: ibm-nginx-svc
    weight: 100
  wildcardPolicy: None
{{- end }}
