apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-software-hub-student2
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/Aditt-197/lab3991.git
    targetRevision: main
    path: helm/install-software-hub
    helm:
      releaseName: software-hub-student2
      valueFiles:
        - ../../overrides/student2/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cpd-student2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=false
